# Generated by Django 5.2.17 on 2026-09-23 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tenancy_and_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='EPSG:2136 or CUSTOM:<id>', max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('srid', models.IntegerField(help_text='SRID in PostGIS spatial_ref_sys', unique=True)),
                ('wkt', models.TextField(help_text='Authoritative definition (WKT2)')),
                ('proj4', models.TextField(help_text='Approximation for web maps (proj4js)')),
                ('kind', models.CharField(choices=[('projected', 'Projected'), ('geographic', 'Geographic')], max_length=12)),
                ('units', models.CharField(help_text="Axis unit, e.g. 'metre', 'Gold Coast foot'", max_length=40)),
                ('unit_to_metre', models.FloatField(help_text='Linear unit in metres; null for degrees', null=True)),
                ('area_of_use', models.CharField(blank=True, max_length=200)),
                ('bounds', models.JSONField(help_text='[west, south, east, north] in degrees', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.district')),
            ],
            options={
                'ordering': ['-is_builtin', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DistrictCrsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_crs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crs.coordinatesystem')),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.district')),
            ],
        ),
        migrations.CreateModel(
            name='SystemCrsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_crs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crs.coordinatesystem')),
            ],
        ),
        migrations.CreateModel(
            name='UserCrsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_crs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crs.coordinatesystem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('pipeline', models.TextField(help_text='PROJ pipeline, axis order x/y (lon/lat, east/north)')),
                ('accuracy_m', models.FloatField(help_text='Stated accuracy in metres, if known', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crs.coordinatesystem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crs.coordinatesystem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_transformation_pair')],
            },
        ),
    ]
