# Generated by Django 5.2.17 on 2026-09-24 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tenancy_and_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasemapSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('xyz', 'XYZ tiles'), ('wms', 'WMS'), ('wmts', 'WMTS'), ('google', 'Google Map Tiles API'), ('bing', 'Bing Maps')], max_length=10)),
                ('preset', models.CharField(blank=True, max_length=40)),
                ('url', models.CharField(blank=True, help_text='XYZ: template with {z}/{x}/{y}; WMS: service URL; WMTS: capabilities URL', max_length=500)),
                ('layers', models.CharField(blank=True, help_text='WMS layer names, WMTS layer id, Google/Bing map type', max_length=200)),
                ('attribution', models.CharField(blank=True, max_length=300)),
                ('min_zoom', models.PositiveSmallIntegerField(default=0)),
                ('max_zoom', models.PositiveSmallIntegerField(default=19)),
                ('requires_key', models.BooleanField(default=False)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('offline_cache_allowed', models.BooleanField(default=False, help_text='True only when the licence allows storing tiles for offline field use')),
                ('notes', models.TextField(blank=True, help_text='Terms of use and other notes')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.district')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
